export const actionTypes = {
  GET_USERS: 'GET_USERS',
  GET_USER: 'GET_USER',
  SET_LOADING: 'SET_LOADING',
  CLEAR_USERS: 'CLEAR_USERS',
  UNAUTHENTICATED_TOKEN: 'UNAUTHENTICATED_TOKEN',
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
};
